services:
  plano:
    image: katanemo/plano:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "11000:11000"
      - "12000:12000"
      - "19901:9901"
    volumes:
      - ${PLANO_CONFIG_FILE:-../demos/getting_started/weather_forecast/config.yaml}:/app/plano_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - ./envoy.template.yaml:/app/envoy.template.yaml
      - ./plano_config_schema.yaml:/app/plano_config_schema.yaml
      - ../cli/planoai/config_generator.py:/app/planoai/config_generator.py
      - ../crates/target/wasm32-wasip1/release/llm_gateway.wasm:/etc/envoy/proxy-wasm-plugins/llm_gateway.wasm
      - ../crates/target/wasm32-wasip1/release/prompt_gateway.wasm:/etc/envoy/proxy-wasm-plugins/prompt_gateway.wasm
      - ~/plano_logs:/var/log/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?error}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:?error}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6379}
      - TALOS_URL=${TALOS_URL:-http://host.docker.internal:8081}
      - TALOS_ADMIN_TOKEN=${TALOS_ADMIN_TOKEN:-}
      - OTEL_TRACING_GRPC_ENDPOINT=http://host.docker.internal:4317
