name: Build and Deploy Documentation
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build and run the Docker container to generate the documentation
      - name: Build documentation using Docker
        run: |
          chmod +x docs/build_docs.sh
          sh docs/build_docs.sh

      - name: Copy CNAME to HTML Build Directory
        run: cp docs/CNAME docs/build/html/CNAME

      # Deploy the docs to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html  # Adjust this path based on where the HTML is generated
          publish_branch: gh-pages
